"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionchunkdelta import (
    ChatCompletionChunkDelta,
    ChatCompletionChunkDeltaTypedDict,
)
from .chatcompletionlogprobs import (
    ChatCompletionLogProbs,
    ChatCompletionLogProbsTypedDict,
)
from .stopreason_union import StopReasonUnion, StopReasonUnionTypedDict
from atoma_sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ChatCompletionChunkChoiceTypedDict(TypedDict):
    r"""Represents the chat completion chunk choice.

    This is used to represent the chat completion chunk choice in the chat completion request.
    """

    delta: ChatCompletionChunkDeltaTypedDict
    r"""Represents the chat completion chunk delta.

    This is used to represent the chat completion chunk delta in the chat completion request.
    It can be either a chat completion chunk delta message or a chat completion chunk delta choice.
    """
    index: int
    r"""The index of this choice in the list of choices."""
    finish_reason: NotRequired[Nullable[str]]
    r"""The reason the chat completion was finished, if applicable."""
    logprobs: NotRequired[Nullable[ChatCompletionLogProbsTypedDict]]
    stop_reason: NotRequired[Nullable[StopReasonUnionTypedDict]]


class ChatCompletionChunkChoice(BaseModel):
    r"""Represents the chat completion chunk choice.

    This is used to represent the chat completion chunk choice in the chat completion request.
    """

    delta: ChatCompletionChunkDelta
    r"""Represents the chat completion chunk delta.

    This is used to represent the chat completion chunk delta in the chat completion request.
    It can be either a chat completion chunk delta message or a chat completion chunk delta choice.
    """

    index: int
    r"""The index of this choice in the list of choices."""

    finish_reason: OptionalNullable[str] = UNSET
    r"""The reason the chat completion was finished, if applicable."""

    logprobs: OptionalNullable[ChatCompletionLogProbs] = UNSET

    stop_reason: OptionalNullable[StopReasonUnion] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["finish_reason", "logprobs", "stop_reason"]
        nullable_fields = ["finish_reason", "logprobs", "stop_reason"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
