"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class ChatCompletionNamedFunctionTypedDict(TypedDict):
    r"""A named function that can be used in a chat completion.

    This is used to represent the named function in the chat completion request.
    """

    name: str
    r"""The name of the function."""


class ChatCompletionNamedFunction(BaseModel):
    r"""A named function that can be used in a chat completion.

    This is used to represent the named function in the chat completion request.
    """

    name: str
    r"""The name of the function."""
