"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionchunkdeltatoolcallfunction import (
    ChatCompletionChunkDeltaToolCallFunction,
    ChatCompletionChunkDeltaToolCallFunctionTypedDict,
)
from atoma_sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ChatCompletionChunkDeltaToolCallTypedDict(TypedDict):
    r"""Represents the chat completion chunk delta tool call.

    This is used to represent the chat completion chunk delta tool call in the chat completion request.
    It can be either a chat completion chunk delta tool call or a chat completion chunk delta tool call function.
    """

    id: str
    r"""The ID of the tool call."""
    index: int
    r"""The index of the tool call."""
    type: str
    r"""The type of the tool call."""
    function: NotRequired[Nullable[ChatCompletionChunkDeltaToolCallFunctionTypedDict]]


class ChatCompletionChunkDeltaToolCall(BaseModel):
    r"""Represents the chat completion chunk delta tool call.

    This is used to represent the chat completion chunk delta tool call in the chat completion request.
    It can be either a chat completion chunk delta tool call or a chat completion chunk delta tool call function.
    """

    id: str
    r"""The ID of the tool call."""

    index: int
    r"""The index of the tool call."""

    type: str
    r"""The type of the tool call."""

    function: OptionalNullable[ChatCompletionChunkDeltaToolCallFunction] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["function"]
        nullable_fields = ["function"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
