"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionlogprob import ChatCompletionLogProb, ChatCompletionLogProbTypedDict
from atoma_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ChatCompletionLogProbsContentTypedDict(TypedDict):
    r"""Represents the chat completion log probs content.

    This is used to represent the chat completion log probs content in the chat completion request.
    It can be either a chat completion log probs content or a chat completion log probs content choice.
    """

    top_logprobs: List[ChatCompletionLogProbTypedDict]


class ChatCompletionLogProbsContent(BaseModel):
    r"""Represents the chat completion log probs content.

    This is used to represent the chat completion log probs content in the chat completion request.
    It can be either a chat completion log probs content or a chat completion log probs content choice.
    """

    top_logprobs: List[ChatCompletionLogProb]
