"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionchunkdeltatoolcall import (
    ChatCompletionChunkDeltaToolCall,
    ChatCompletionChunkDeltaToolCallTypedDict,
)
from atoma_sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class ChatCompletionChunkDeltaTypedDict(TypedDict):
    r"""Represents the chat completion chunk delta.

    This is used to represent the chat completion chunk delta in the chat completion request.
    It can be either a chat completion chunk delta message or a chat completion chunk delta choice.
    """

    content: NotRequired[Nullable[str]]
    r"""The content of the message, if present in this chunk."""
    reasoning_content: NotRequired[Nullable[str]]
    r"""The reasoning content, if present in this chunk."""
    role: NotRequired[Nullable[str]]
    r"""The role of the message author, if present in this chunk."""
    tool_calls: NotRequired[Nullable[List[ChatCompletionChunkDeltaToolCallTypedDict]]]
    r"""The tool calls information, if present in this chunk."""


class ChatCompletionChunkDelta(BaseModel):
    r"""Represents the chat completion chunk delta.

    This is used to represent the chat completion chunk delta in the chat completion request.
    It can be either a chat completion chunk delta message or a chat completion chunk delta choice.
    """

    content: OptionalNullable[str] = UNSET
    r"""The content of the message, if present in this chunk."""

    reasoning_content: OptionalNullable[str] = UNSET
    r"""The reasoning content, if present in this chunk."""

    role: OptionalNullable[str] = UNSET
    r"""The role of the message author, if present in this chunk."""

    tool_calls: OptionalNullable[List[ChatCompletionChunkDeltaToolCall]] = UNSET
    r"""The tool calls information, if present in this chunk."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["content", "reasoning_content", "role", "tool_calls"]
        nullable_fields = ["content", "reasoning_content", "role", "tool_calls"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
