"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionnamedfunction import (
    ChatCompletionNamedFunction,
    ChatCompletionNamedFunctionTypedDict,
)
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class ChatCompletionNamedToolChoiceParamTypedDict(TypedDict):
    r"""A named tool choice that can be used in a chat completion.

    This is used to represent the named tool choice in the chat completion request.
    """

    function: ChatCompletionNamedFunctionTypedDict
    r"""A named function that can be used in a chat completion.

    This is used to represent the named function in the chat completion request.
    """
    type: str
    r"""The type of the tool choice."""


class ChatCompletionNamedToolChoiceParam(BaseModel):
    r"""A named tool choice that can be used in a chat completion.

    This is used to represent the named tool choice in the chat completion request.
    """

    function: ChatCompletionNamedFunction
    r"""A named function that can be used in a chat completion.

    This is used to represent the named function in the chat completion request.
    """

    type: str
    r"""The type of the tool choice."""
