"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict
from typing_extensions import NotRequired, TypedDict


class ChatCompletionToolFunctionParamTypedDict(TypedDict):
    r"""A function that can be used in a chat completion."""

    name: str
    r"""The name of the function."""
    description: NotRequired[Nullable[str]]
    r"""The description of the function."""
    parameters: NotRequired[Nullable[Dict[str, Any]]]
    r"""The parameters of the function."""
    strict: NotRequired[Nullable[bool]]
    r"""Whether to strictly validate the parameters of the function."""


class ChatCompletionToolFunctionParam(BaseModel):
    r"""A function that can be used in a chat completion."""

    name: str
    r"""The name of the function."""

    description: OptionalNullable[str] = UNSET
    r"""The description of the function."""

    parameters: OptionalNullable[Dict[str, Any]] = UNSET
    r"""The parameters of the function."""

    strict: OptionalNullable[bool] = UNSET
    r"""Whether to strictly validate the parameters of the function."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["description", "parameters", "strict"]
        nullable_fields = ["description", "parameters", "strict"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
