"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionlogprobscontent import (
    ChatCompletionLogProbsContent,
    ChatCompletionLogProbsContentTypedDict,
)
from atoma_sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class ChatCompletionLogProbsTypedDict(TypedDict):
    r"""Represents the chat completion log probs.

    This is used to represent the chat completion log probs in the chat completion request.
    It can be either a chat completion log probs or a chat completion log probs choice.
    """

    content: NotRequired[Nullable[List[ChatCompletionLogProbsContentTypedDict]]]
    r"""The log probs of the chat completion."""


class ChatCompletionLogProbs(BaseModel):
    r"""Represents the chat completion log probs.

    This is used to represent the chat completion log probs in the chat completion request.
    It can be either a chat completion log probs or a chat completion log probs choice.
    """

    content: OptionalNullable[List[ChatCompletionLogProbsContent]] = UNSET
    r"""The log probs of the chat completion."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["content"]
        nullable_fields = ["content"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
