"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletiontoolfunctionparam import (
    ChatCompletionToolFunctionParam,
    ChatCompletionToolFunctionParamTypedDict,
)
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class ChatCompletionToolsParamTypedDict(TypedDict):
    r"""A tool that can be used in a chat completion."""

    function: ChatCompletionToolFunctionParamTypedDict
    r"""A function that can be used in a chat completion."""
    type: str
    r"""The type of the tool."""


class ChatCompletionToolsParam(BaseModel):
    r"""A tool that can be used in a chat completion."""

    function: ChatCompletionToolFunctionParam
    r"""A function that can be used in a chat completion."""

    type: str
    r"""The type of the tool."""
