"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionchunk import ChatCompletionChunk, ChatCompletionChunkTypedDict
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class ChatCompletionsCreateStreamResponseBodyTypedDict(TypedDict):
    r"""Chat completions"""

    data: ChatCompletionChunkTypedDict
    r"""Represents the chat completion chunk.

    This is used to represent the chat completion chunk in the chat completion request.
    It can be either a chat completion chunk or a chat completion chunk choice.
    """


class ChatCompletionsCreateStreamResponseBody(BaseModel):
    r"""Chat completions"""

    data: ChatCompletionChunk
    r"""Represents the chat completion chunk.

    This is used to represent the chat completion chunk in the chat completion request.
    It can be either a chat completion chunk or a chat completion chunk choice.
    """
