"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .completionsstreamresponse import (
    CompletionsStreamResponse,
    CompletionsStreamResponseTypedDict,
)
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class CompletionsCreateStreamResponseBodyTypedDict(TypedDict):
    r"""Completions"""

    data: CompletionsStreamResponseTypedDict


class CompletionsCreateStreamResponseBody(BaseModel):
    r"""Completions"""

    data: CompletionsStreamResponse
