"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .prompttokensdetails import PromptTokensDetails, PromptTokensDetailsTypedDict
from atoma_sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class CompletionUsageTypedDict(TypedDict):
    r"""Represents the completion usage.

    This is used to represent the completion usage in the chat completion request.
    It can be either a completion usage or a completion chunk usage.
    """

    completion_tokens: int
    r"""Number of tokens in the completion."""
    prompt_tokens: int
    r"""Number of tokens in the prompt."""
    total_tokens: int
    r"""Total number of tokens used (prompt + completion)."""
    prompt_tokens_details: NotRequired[Nullable[PromptTokensDetailsTypedDict]]


class CompletionUsage(BaseModel):
    r"""Represents the completion usage.

    This is used to represent the completion usage in the chat completion request.
    It can be either a completion usage or a completion chunk usage.
    """

    completion_tokens: int
    r"""Number of tokens in the completion."""

    prompt_tokens: int
    r"""Number of tokens in the prompt."""

    total_tokens: int
    r"""Total number of tokens used (prompt + completion)."""

    prompt_tokens_details: OptionalNullable[PromptTokensDetails] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["prompt_tokens_details"]
        nullable_fields = ["prompt_tokens_details"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
