"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import List, Union
from typing_extensions import TypeAliasType


CompletionsPromptTypedDict = TypeAliasType(
    "CompletionsPromptTypedDict", Union[str, List[str], List[int], List[List[int]]]
)


CompletionsPrompt = TypeAliasType(
    "CompletionsPrompt", Union[str, List[str], List[int], List[List[int]]]
)
