"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class CompletionTokensDetailsTypedDict(TypedDict):
    r"""The details of the completion tokens"""

    accepted_prediction_tokens: int
    r"""The number of tokens in the completion"""
    audio_tokens: int
    r"""The number of audio tokens"""
    reasoning_tokens: int
    r"""The number of reasoning tokens"""
    rejected_prediction_tokens: int
    r"""The number of rejected prediction tokens"""


class CompletionTokensDetails(BaseModel):
    r"""The details of the completion tokens"""

    accepted_prediction_tokens: int
    r"""The number of tokens in the completion"""

    audio_tokens: int
    r"""The number of audio tokens"""

    reasoning_tokens: int
    r"""The number of reasoning tokens"""

    rejected_prediction_tokens: int
    r"""The number of rejected prediction tokens"""
