"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .completionchoice import CompletionChoice, CompletionChoiceTypedDict
from atoma_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class CompletionsStreamResponseTypedDict(TypedDict):
    choices: List[CompletionChoiceTypedDict]
    r"""Array of completion choices response"""
    created: int
    r"""The creation time of the request"""
    id: str
    r"""The ID of the request"""
    model: str
    r"""The model used for the request"""
    object: str
    r"""The object type"""
    system_fingerprint: str
    r"""The system fingerprint"""


class CompletionsStreamResponse(BaseModel):
    choices: List[CompletionChoice]
    r"""Array of completion choices response"""

    created: int
    r"""The creation time of the request"""

    id: str
    r"""The ID of the request"""

    model: str
    r"""The model used for the request"""

    object: str
    r"""The object type"""

    system_fingerprint: str
    r"""The system fingerprint"""
