"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .confidentialcomputestreamresponse import (
    ConfidentialComputeStreamResponse,
    ConfidentialComputeStreamResponseTypedDict,
)
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class ConfidentialChatCompletionsCreateStreamResponseBodyTypedDict(TypedDict):
    r"""Chat completions"""

    data: ConfidentialComputeStreamResponseTypedDict
    r"""Represents a response from a confidential compute request"""


class ConfidentialChatCompletionsCreateStreamResponseBody(BaseModel):
    r"""Chat completions"""

    data: ConfidentialComputeStreamResponse
    r"""Represents a response from a confidential compute request"""
