"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class ImageDataTypedDict(TypedDict):
    r"""Individual image data in the response"""

    revised_prompt: str
    url: str


class ImageData(BaseModel):
    r"""Individual image data in the response"""

    revised_prompt: str

    url: str
