"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class JSONSchemaResponseFormatTypedDict(TypedDict):
    r"""The format to return the response in.

    This is used to represent the format to return the response in in the chat completion request.
    It can be either text, json_object, or json_schema.
    """

    name: str
    r"""The name of the response format."""
    description: NotRequired[Nullable[str]]
    r"""The description of the response format."""
    schema_: NotRequired[Any]
    r"""The JSON schema of the response format."""
    strict: NotRequired[Nullable[bool]]
    r"""Whether to strictly validate the JSON schema."""


class JSONSchemaResponseFormat(BaseModel):
    r"""The format to return the response in.

    This is used to represent the format to return the response in in the chat completion request.
    It can be either text, json_object, or json_schema.
    """

    name: str
    r"""The name of the response format."""

    description: OptionalNullable[str] = UNSET
    r"""The description of the response format."""

    schema_: Annotated[Optional[Any], pydantic.Field(alias="schema")] = None
    r"""The JSON schema of the response format."""

    strict: OptionalNullable[bool] = UNSET
    r"""Whether to strictly validate the JSON schema."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["description", "schema", "strict"]
        nullable_fields = ["description", "strict"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
