"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel
from typing import Dict, List
from typing_extensions import TypedDict


class LogProbsTypedDict(TypedDict):
    text_offset: List[int]
    r"""The text offset of the tokens"""
    token_logprobs: List[float]
    r"""The log probabilities of the tokens"""
    tokens: List[str]
    r"""The tokens"""
    top_logprobs: List[Dict[str, float]]
    r"""The top log probabilities"""


class LogProbs(BaseModel):
    text_offset: List[int]
    r"""The text offset of the tokens"""

    token_logprobs: List[float]
    r"""The log probabilities of the tokens"""

    tokens: List[str]
    r"""The tokens"""

    top_logprobs: List[Dict[str, float]]
    r"""The top log probabilities"""
