"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagecontentpart_union import (
    MessageContentPartUnion,
    MessageContentPartUnionTypedDict,
)
from typing import List, Union
from typing_extensions import TypeAliasType


MessageContentTypedDict = TypeAliasType(
    "MessageContentTypedDict", Union[str, List[MessageContentPartUnionTypedDict]]
)
r"""Represents the content of a message.

This is used to represent the content of a message in the chat completion request.
It can be either a text or an array of content parts.
"""


MessageContent = TypeAliasType(
    "MessageContent", Union[str, List[MessageContentPartUnion]]
)
r"""Represents the content of a message.

This is used to represent the content of a message in the chat completion request.
It can be either a text or an array of content parts.
"""
