"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel
from atoma_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class NodesModelsRetrieveRequestTypedDict(TypedDict):
    model: str
    r"""The name of the model to retrieve"""


class NodesModelsRetrieveRequest(BaseModel):
    model: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The name of the model to retrieve"""
