"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class NodesCreateLockRequestTypedDict(TypedDict):
    r"""Request body for creating a node lock"""

    model: str
    r"""The model to lock a node for"""
    max_num_tokens: NotRequired[Nullable[int]]
    r"""The number of tokens to be processed for confidential compute
    (including input and output tokens)
    """
    timeout: NotRequired[Nullable[int]]
    r"""An optional timeout period for the locked compute units, in seconds"""


class NodesCreateLockRequest(BaseModel):
    r"""Request body for creating a node lock"""

    model: str
    r"""The model to lock a node for"""

    max_num_tokens: OptionalNullable[int] = UNSET
    r"""The number of tokens to be processed for confidential compute
    (including input and output tokens)
    """

    timeout: OptionalNullable[int] = UNSET
    r"""An optional timeout period for the locked compute units, in seconds"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["max_num_tokens", "timeout"]
        nullable_fields = ["max_num_tokens", "timeout"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
