"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class PromptTokensDetailsTypedDict(TypedDict):
    audio_tokens: int
    r"""The number of audio tokens"""
    cached_tokens: int
    r"""The number of cached tokens"""


class PromptTokensDetails(BaseModel):
    audio_tokens: int
    r"""The number of audio tokens"""

    cached_tokens: int
    r"""The number of cached tokens"""
