"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class SelectNodePublicKeyRequestTypedDict(TypedDict):
    r"""The request body for selecting a node's public key for encryption
    from a client.
    """

    model_name: str
    r"""The request model name"""


class SelectNodePublicKeyRequest(BaseModel):
    r"""The request body for selecting a node's public key for encryption
    from a client.
    """

    model_name: str
    r"""The request model name"""
