"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class ToolCallFunctionTypedDict(TypedDict):
    r"""Represents the function that the model called.

    This is used to represent the function that the model called in the chat completion request.
    It can be either a function or a tool call.
    """

    arguments: str
    r"""The arguments to call the function with, as generated by the model in JSON format.
    Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema.
    Validate the arguments in your code before calling your function.
    """
    name: str
    r"""The name of the function to call."""


class ToolCallFunction(BaseModel):
    r"""Represents the function that the model called.

    This is used to represent the function that the model called in the chat completion request.
    It can be either a function or a tool call.
    """

    arguments: str
    r"""The arguments to call the function with, as generated by the model in JSON format.
    Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema.
    Validate the arguments in your code before calling your function.
    """

    name: str
    r"""The name of the function to call."""
