"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ToolChoiceLiteral(str, Enum):
    r"""A literal tool choice that can be used in a chat completion.

    This is used to represent the literal tool choice in the chat completion request.
    It can be either none or auto.
    """

    NONE = "none"
    AUTO = "auto"
