"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .toolcallfunction import ToolCallFunction, ToolCallFunctionTypedDict
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class ToolCallTypedDict(TypedDict):
    r"""Represents the tool call that the model made.

    This is used to represent the tool call that the model made in the chat completion request.
    It can be either a function or a tool.
    """

    function: ToolCallFunctionTypedDict
    r"""Represents the function that the model called.

    This is used to represent the function that the model called in the chat completion request.
    It can be either a function or a tool call.
    """
    id: str
    r"""The ID of the tool call."""
    type: str
    r"""The type of the tool. Currently, only function is supported."""


class ToolCall(BaseModel):
    r"""Represents the tool call that the model made.

    This is used to represent the tool call that the model made in the chat completion request.
    It can be either a function or a tool.
    """

    function: ToolCallFunction
    r"""Represents the function that the model called.

    This is used to represent the function that the model called in the chat completion request.
    It can be either a function or a tool call.
    """

    id: str
    r"""The ID of the tool call."""

    type: str
    r"""The type of the tool. Currently, only function is supported."""
