"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionnamedtoolchoiceparam import (
    ChatCompletionNamedToolChoiceParam,
    ChatCompletionNamedToolChoiceParamTypedDict,
)
from .toolchoiceliteral import ToolChoiceLiteral
from typing import Union
from typing_extensions import TypeAliasType


ToolChoiceTypedDict = TypeAliasType(
    "ToolChoiceTypedDict",
    Union[ChatCompletionNamedToolChoiceParamTypedDict, ToolChoiceLiteral],
)
r"""A tool choice that can be used in a chat completion.

This is used to represent the tool choice in the chat completion request.
It can be either a literal tool choice or a named tool choice.
"""


ToolChoice = TypeAliasType(
    "ToolChoice", Union[ChatCompletionNamedToolChoiceParam, ToolChoiceLiteral]
)
r"""A tool choice that can be used in a chat completion.

This is used to represent the tool choice in the chat completion request.
It can be either a literal tool choice or a named tool choice.
"""
