"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .completiontokensdetails import (
    CompletionTokensDetails,
    CompletionTokensDetailsTypedDict,
)
from .prompttokensdetails import PromptTokensDetails, PromptTokensDetailsTypedDict
from atoma_sdk.types import BaseModel
from typing_extensions import TypedDict


class UsageTypedDict(TypedDict):
    completion_tokens: int
    r"""The number of completion tokens used"""
    completion_tokens_details: CompletionTokensDetailsTypedDict
    r"""The details of the completion tokens"""
    prompt_tokens: int
    r"""The number of prompt tokens used"""
    prompt_tokens_details: PromptTokensDetailsTypedDict
    total_tokens: int
    r"""The total number of tokens used"""


class Usage(BaseModel):
    completion_tokens: int
    r"""The number of completion tokens used"""

    completion_tokens_details: CompletionTokensDetails
    r"""The details of the completion tokens"""

    prompt_tokens: int
    r"""The number of prompt tokens used"""

    prompt_tokens_details: PromptTokensDetails

    total_tokens: int
    r"""The total number of tokens used"""
