workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    atoma-proxy:
        inputs:
            - location: ../atoma-proxy/atoma-proxy/docs/openapi.yml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/atoma/test/atoma-proxy
targets:
    atoma-sdk:
        target: python
        source: atoma-proxy
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/atoma/test/atoma-proxy-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
